version: "3.9"

services:
  api:
    build: .
    command: uvicorn cards.api:app --host 0.0.0.0 --port 8000
    environment:
      - CARDS_DB_URL=sqlite:///./data/card_printing.db
      - CARDS_EXPORT_DIR=/app/exports
      - CARDS_TIMEZONE=America/Los_Angeles
    volumes:
      - ./exports:/app/exports
      - ./data:/app/data
    ports:
      - "8000:8000"

  streamlit:
    build: .
    command: streamlit run cards/streamlit_app.py --server.address=0.0.0.0 --server.port=8501
    environment:
      - CARDS_DB_URL=sqlite:///./data/card_printing.db
      - CARDS_EXPORT_DIR=/app/exports
      - CARDS_TIMEZONE=America/Los_Angeles
    depends_on:
      - api
    volumes:
      - ./exports:/app/exports
      - ./data:/app/data
    ports:
      - "8501:8501"
