name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Lint
        run: ruff check .
      - name: Type check
        run: mypy cards
      - name: Tests
        run: pytest
      - name: Build Streamlit artifact
        run: |
          mkdir -p build
          streamlit run cards/streamlit_app.py --server.headless true --server.port 8501 &
          STREAMLIT_PID=$!
          sleep 10
          kill $STREAMLIT_PID || true
          echo "Streamlit build completed" > build/README.txt
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: streamlit-build
          path: build
